### ISSUE TITLE
Minimal <input> example

### ISSUE THREAD

**Issue by adelriosantiago** [widmogrod/js-crdt#33]
Is there some kind of "minimal example" using an <input> element?

**Comment by widmogrod** [comment]
@adelriosantiago only example that I know is this https://github.com/widmogrod/notepad-app which for capturing changes and rendering collaborative cursor use https://github.com/quilljs/quill 

For minimal `<input>` you should be wary,  If you consider witting it by yourself you would need to implement
- input changes capturing (diffs)
- multiple collaborative cursors

Maybe quill, can work on input? 
That would simplify this.
